build:
  image: armdrone/drone-docker
  environment:
    - DOCKER_HOST=tcp://localhost:2375
  commands:
    - apk update && apk add git ca-certificates make
    - export VERSION=$(cat VERSION)
    - make

notify:
  slack:
    webhook_url: $$SLACK_WEBHOOK_URL
    channel: buildstatus
    username: Drone
    when:
      started: false
      success: true
      failure: true
