build:
  image: firecyberice/rpi-docker:1.10.0-dev
  extra_hosts:
    - docker
  environment:
    - DOCKER_HOST=tcp://localhost:2375

compose:
  docker:
    privileged: true
    image: firecyberice/rpi-docker:1.10.0-dev-dind

publish:
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: hypriot/rpi-node
    tag:
      - '4.3.1'
      - '4.3'
      - '4'
      - argon
    file: 4.3/Dockerfile
    when:
      branch: master

  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: hypriot/rpi-node
    tag:
      - 4.3.1-onbuild
      - 4.3-onbuild
      - 4-onbuild
      - argon-onbuild
    file: 4.3/onbuild/Dockerfile
    when:
      branch: master

  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: hypriot/rpi-node
    tag:
      - 4.3.1-wheezy
      - 4.3-wheezy
      - 4-wheezy
      - argon-wheezy
    file: 4.3/wheezy/Dockerfile
    when:
      branch: master

  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: hypriot/rpi-node
    tag:
      - 4.3.1-slim
      - 4.3-slim
      - 4-slim
    file: 4.3/slim/Dockerfile
    when:
      branch: master

  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: hypriot/rpi-node
    tag:
      - '5.6.0'
      - '5.6'
      - '5'
      - latest
    file: 5.6/Dockerfile
    when:
      branch: master

  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: hypriot/rpi-node
    tag:
      - 5.6.0-onbuild
      - 5.6-onbuild
      - 5-onbuild
      - onbuild
    file: 5.6/onbuild/Dockerfile
    when:
      branch: master

  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: hypriot/rpi-node
    tag:
      - 5.6.0-wheezy
      - 5.6-wheezy
      - 5-wheezy
      - wheezy
    file: 5.6/wheezy/Dockerfile
    when:
      branch: master

  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: hypriot/rpi-node
    tag:
      - 5.6.0-slim
      - 5.6-slim
      - 5-slim
      - slim
    file: 5.6/slim/Dockerfile
    when:
      branch: master

notify:
  slack:
    webhook_url: $$SLACK_WEBHOOK_URL
    channel: buildstatus
    username: Drone
    when:
      started: false
      success: true
      failure: true
