build:
  image: firecyberice/rpi-docker:1.10.0-dev
  extra_hosts:
    - docker
  environment:
    - DOCKER_HOST=tcp://localhost:2375

compose:
  docker:
    privileged: true
    image: firecyberice/rpi-docker:1.10.0-dev-dind

publish:
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: hypriot/rpi-node
    tag:
      - '4.5.0'
      - '4.5'
      - '4'
      - argon
    file: 4.5/Dockerfile
    when:
      branch: master

  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: hypriot/rpi-node
    tag:
      - 4.5.0-onbuild
      - 4.5-onbuild
      - 4-onbuild
      - argon-onbuild
    file: 4.5/onbuild/Dockerfile
    when:
      branch: master

  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: hypriot/rpi-node
    tag:
      - 4.5.0-wheezy
      - 4.5-wheezy
      - 4-wheezy
      - argon-wheezy
    file: 4.5/wheezy/Dockerfile
    when:
      branch: master

  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: hypriot/rpi-node
    tag:
      - 4.5.0-slim
      - 4.5-slim
      - 4-slim
    file: 4.5/slim/Dockerfile
    when:
      branch: master

  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: hypriot/rpi-node
    tag:
      - '6.5.0'
      - '6.5'
      - '6'
      - latest
    file: 6.5/Dockerfile
    when:
      branch: master

  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: hypriot/rpi-node
    tag:
      - 6.5.0-onbuild
      - 6.5-onbuild
      - 6-onbuild
      - onbuild
    file: 6.5/onbuild/Dockerfile
    when:
      branch: master

  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: hypriot/rpi-node
    tag:
      - 6.5.0-wheezy
      - 6.5-wheezy
      - 6-wheezy
      - wheezy
    file: 6.5/wheezy/Dockerfile
    when:
      branch: master

  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: hypriot/rpi-node
    tag:
      - 6.5.0-slim
      - 6.5-slim
      - 6-slim
      - slim
    file: 6.5/slim/Dockerfile
    when:
      branch: master

notify:
  slack:
    webhook_url: $$SLACK_WEBHOOK_URL
    channel: buildstatus
    username: Drone
    when:
      started: false
      success: true
      failure: true
