
matrix:
  FLAVOR:
    - -slim-test
    - -onbuild-test
    - -wheezy-test
    - ""

publish:
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: hypriot/rpi-node
    tag:
      - '4.2.3'$$FLAVOR
      - '4.2'$$FLAVOR
      - '4'$$FLAVOR
      - argon$$FLAVOR
    file: 4.2/$$FLAVOR/Dockerfile
    when:
      branch:
        - matrixbuild
        - master

  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: hypriot/rpi-node
    tag:
      - '5.3.0'$$FLAVOR
      - '5.3'$$FLAVOR
      - '5'$$FLAVOR
      - $$FLAVOR
    file: 5.3/$$FLAVOR/Dockerfile
    when:
      branch:
        - matrixbuild
        - master

notify:
  slack:
    webhook_url: $$SLACK_WEBHOOK_URL
    channel: buildstatus
    username: Drone
    when:
      started: false
      success: true
      failure: true
